### ISSUE TITLE
Helm chart for VPA-exporter

### ISSUE THREAD

**Issue by rajivchirania** [gardener/vpa-exporter#12]
Do we have a helm chart available for VPA-exporter

**Comment by amshuman-kr** [comment]
Not here but in the [gardener/gardener](https://github.com/gardener/gardener/) repo. But it is a bit all over the place 😅

- https://github.com/gardener/gardener/blob/master/charts/seed-bootstrap/charts/vpa/charts/application/templates/clusterrole-exporter.yaml
- https://github.com/gardener/gardener/blob/master/charts/seed-bootstrap/charts/vpa/charts/application/templates/clusterrolebinding-exporter.yaml
- https://github.com/gardener/gardener/blob/master/charts/seed-bootstrap/charts/vpa/charts/application/templates/serviceaccount-exporter.yaml
- https://github.com/gardener/gardener/blob/master/charts/seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-exporter.yaml
- https://github.com/gardener/gardener/blob/master/charts/seed-bootstrap/charts/vpa/charts/runtime/templates/service-exporter.yaml

PS: We plan to discontinue this project in favour of [`kube-state-metrics`](https://github.com/kubernetes/kube-state-metrics) which now has an [optional support](https://github.com/kubernetes/kube-state-metrics#enabling-verticalpodautoscalers) for `VPA` metrics.

**Comment by amshuman-kr** [comment]
@rajivchirania Can I close this issue?

**Comment by rajivchirania** [comment]
@amshuman-kr yes please
