### ISSUE TITLE
[Feature] Release a container image for vpa-exporter

### ISSUE THREAD

**Issue by patrickshan** [gardener/vpa-exporter#13]
**Feature (What you would like to be added):**
Release a container image for vpa-exporter as part of release assets. 

**Motivation (Why is this needed?):**
Usually vpa-exporter will be deployed inside a kubernetes cluster. It would be easier for the deployment if there is a container image coming with a release.

**Approach/Hint to the implement solution (optional):**
This can be done through github Actions along with github container registry ghcr.io.

**Comment by ialidzhikov** [comment]
Container images are actually released and maintained under  `eu.gcr.io/gardener-project/gardener/vpa-exporter`.

```
$ docker pull eu.gcr.io/gardener-project/gardener/vpa-exporter:0.1.5
0.1.5: Pulling from gardener-project/gardener/vpa-exporter
5d20c808ce19: Pull complete
6e867f6900ae: Pull complete
911ddcd81a4f: Pull complete
Digest: sha256:7954cbbe8b1f2eb8f388e2141978b5402f69c7573fd3a74ade114ba515a4d73b
Status: Downloaded newer image for eu.gcr.io/gardener-project/gardener/vpa-exporter:0.1.5
eu.gcr.io/gardener-project/gardener/vpa-exporter:0.1.5
```

**Comment by ialidzhikov** [comment]
I asked @istvanballok and @wyb1 to put the container image in the release description as we do for other components - see for example https://github.com/gardener/gardener-extension-provider-aws/releases/tag/v1.19.1.

**Comment by ialidzhikov** [comment]
I am closing this issue. Feel free to reopen if you have further questions/objections.

/close
